project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hello, I'm Dover. Yuning"
  site-url: https://doveryuning.github.io
  favicon: misc/info/bo.png
  repo-url: https://doveryuning.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Dover Yuning"
    right: 
      - icon: github
        href: https://doveryuning.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
     
      - text: "Research"
        href: research/research.qmd

      - text: "Teaching"
        href: teaching/teaching.qmd

      - text: "Talks"
        href: talks/talks.qmd

      - text: "Blog/notes"
        href: blog/blog.qmd
        
      - text: "About me"
        href: about_me.qmd
        
      #- text: "CV"
      #  href: misc/info/CV-CZ-2407.pdf


format:
  html:
    theme: styles.scss


